### ISSUE TITLE
[ISSUE] Chore Approvals? Ok: None. Cant clear non existant chore approval

### ISSUE THREAD

**Issue by AustinSoundsOK** [ad-ha/kidschores-ha#87]
### Home Assistant Version

2025.2.5

### KidsChore Integration Version

0.2.2

### Installation Method

HACS

### Did you check for existing issues?

- [x] Yes, I have checked for existing issues
- [ ] No, I have not checked for existing issues

### Did you enable debug logging before and are ready to post logs?

- [x] Yes, I have enabled debug logging
- [ ] No, I have not enabled debug logging

### Describe the Issue

I have an issue that there is a pending chore approval that just says either "Ok: None" and "No: None." In developer tools, when I check the entity state and attributes for sensor.kc_global_chore_pending_approvals it says there are 11 pending approvals that say 

```
- chore_name: Unknown Chore
  Claimed on: '2025-02-23T22:30:39.240370+00:00'
```

I have cleared the attribute data and state from the developer tools, but they keep returning on their own.

Here are some screen shots of the issue: 

![Image](https://github.com/user-attachments/assets/98959927-2d1c-4300-9854-c0229149619f)

![Image](https://github.com/user-attachments/assets/6b10ae27-c112-4cc2-9f08-55f04436e5e9)

### Logs
```
2025-02-24 08:55:34.335 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration kidschores which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-24 08:55:34.337 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-24 08:55:34.339 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration better_thermostat which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-24 08:55:34.340 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration pirateweather which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-24 08:55:34.342 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration midea_dehumidifier_lan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-24 08:55:34.344 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nws_alerts which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-24 08:55:34.345 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration wyzeapi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-24 08:55:34.347 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration sleep_as_android which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-24 08:55:34.349 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration spotcast which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-24 08:55:34.350 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration moonraker which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-24 08:55:34.353 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tapo_control which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-24 08:55:46.708 INFO (MainThread) [custom_components.kidschores] Starting setup for KidsChores entry: 01JMQ79VZR5GPFD7T5KDAN06RS
2025-02-24 08:55:46.708 DEBUG (MainThread) [custom_components.kidschores] KidsChoresStorageManager: Loading data from storage
2025-02-24 08:55:46.713 INFO (MainThread) [custom_components.kidschores] Storage data loaded successfully
2025-02-24 08:55:46.714 INFO (MainThread) [custom_components.kidschores] Chore data migration complete.
2025-02-24 08:55:46.715 DEBUG (MainThread) [custom_components.kidschores] Updated kid 'Nora' with ID: 9e7b63fe-8a0b-436d-a14a-85fd201c62b6
2025-02-24 08:55:46.715 DEBUG (MainThread) [custom_components.kidschores] Updated kid 'Elliot' with ID: a4521b1a-43bf-44bb-a222-154521bdd012
2025-02-24 08:55:46.715 DEBUG (MainThread) [custom_components.kidschores] Updated parent 'Dad' with ID: a9f31d27-9a1c-43fa-8e16-510d0a5c707e
2025-02-24 08:55:46.715 DEBUG (MainThread) [custom_components.kidschores] Updated chore 'Bring Out Recycling' with ID: 006502b4-58d8-4c6b-bb9b-e86def0de528
2025-02-24 08:55:46.715 DEBUG (MainThread) [custom_components.kidschores] Updated chore 'Clean Little Bathroom' with ID: 0aaacc36-6c59-4a51-bcf2-5046223dfcd4
2025-02-24 08:55:46.715 DEBUG (MainThread) [custom_components.kidschores] Updated chore 'Brush Your Teeth In the Morning' with ID: 0ce0246b-f1f3-4d5d-baf6-df7d7fd0e1e6
2025-02-24 08:55:46.716 DEBUG (MainThread) [custom_components.kidschores] Updated chore 'Put Away All Stuffies' with ID: 280a01fb-d441-46e8-b130-d9e1e9592aca
2025-02-24 08:55:46.716 DEBUG (MainThread) [custom_components.kidschores] Updated chore 'Water for Zola' with ID: 3a3247fe-1346-466f-bd38-6be7bd2d1449
2025-02-24 08:55:46.716 DEBUG (MainThread) [custom_components.kidschores] Updated chore 'Clean the Bathroom' with ID: 62487dd1-c14d-459b-a6ff-b19a77746f5e
2025-02-24 08:55:46.716 DEBUG (MainThread) [custom_components.kidschores] Updated chore 'Empty Dishwasher' with ID: 66359d3b-83ff-482d-bcb0-5922956e993f
2025-02-24 08:55:46.716 DEBUG (MainThread) [custom_components.kidschores] Updated chore 'Clean Kitchen' with ID: 75a255fb-1031-4caa-b1ae-df88f828af41
2025-02-24 08:55:46.716 DEBUG (MainThread) [custom_components.kidschores] Updated chore 'Clean Bedroom' with ID: 7c7a456a-6992-44a8-a96b-c5a2e5b46e88
2025-02-24 08:55:46.716 DEBUG (MainThread) [custom_components.kidschores] Updated chore 'Load Dishwasher' with ID: 997703c3-ca27-4cfa-bd56-03dc841ea5da
2025-02-24 08:55:46.716 DEBUG (MainThread) [custom_components.kidschores] Updated chore 'Brush Hair' with ID: a5c511fc-b49d-4568-8096-4b074601b54c
2025-02-24 08:55:46.716 DEBUG (MainThread) [custom_components.kidschores] Updated chore 'Brush Your Teeth at Night' with ID: c2a878eb-2d7d-4384-94ad-c0c50a06610c
2025-02-24 08:55:46.717 DEBUG (MainThread) [custom_components.kidschores] Updated chore 'Put Away Laundry' with ID: d5af2513-86d4-4912-ab1d-3de1c69a74ad
2025-02-24 08:55:46.717 DEBUG (MainThread) [custom_components.kidschores] Updated chore 'Walk Zola' with ID: e04b954c-82aa-497a-bab0-85b312892811
2025-02-24 08:55:46.717 DEBUG (MainThread) [custom_components.kidschores] Updated chore 'Feed Zola' with ID: f4f323b5-7619-4e12-a308-a6415964f11c
2025-02-24 08:55:46.717 DEBUG (MainThread) [custom_components.kidschores] Updated chore 'Bring Garbage Out' with ID: f8d841b8-05ce-41a4-a44d-fdd1d0639ba7
2025-02-24 08:55:46.717 DEBUG (MainThread) [custom_components.kidschores] Updated chore 'Clean Living Room' with ID: fa2fd4e8-0b78-4f2c-9226-bcf3b00f91ec
2025-02-24 08:55:46.718 DEBUG (MainThread) [custom_components.kidschores] Updated badge 'Super Clean' with ID: 0d6a91ae-1696-4a60-bc13-f858ec627d35
2025-02-24 08:55:46.719 DEBUG (MainThread) [custom_components.kidschores] Updated badge 'woah' with ID: 57dced02-818d-45bf-bca0-82a978b06873
2025-02-24 08:55:46.719 DEBUG (MainThread) [custom_components.kidschores] Updated badge 'Mr Duckie' with ID: 7da1311c-3c6f-4480-ace3-a908b13372b5
2025-02-24 08:55:46.719 DEBUG (MainThread) [custom_components.kidschores] Updated badge 'mr clean' with ID: 88813485-ec80-4526-ad0a-416b1344190d
2025-02-24 08:55:46.719 DEBUG (MainThread) [custom_components.kidschores] Updated badge 'Hot Streak' with ID: a07c425c-d4e6-4550-8fef-9a77987a00a8
2025-02-24 08:55:46.719 DEBUG (MainThread) [custom_components.kidschores] Updated badge 'do one chore' with ID: b9b2cc9a-a72b-4466-a3f9-dea453a996a4
2025-02-24 08:55:46.719 DEBUG (MainThread) [custom_components.kidschores] Updated badge 'Chore Master' with ID: c58304e5-e653-4b66-b2e0-aca433d6ae2c
2025-02-24 08:55:46.719 DEBUG (MainThread) [custom_components.kidschores] Updated reward 'TV for evening' with ID: 4b621554-f995-40a6-8311-e5f20780e597
2025-02-24 08:55:46.719 DEBUG (MainThread) [custom_components.kidschores] Updated reward 'Stuffie!' with ID: 88ee552b-0fbf-4682-b0c3-2c48f8476caa
2025-02-24 08:55:46.720 DEBUG (MainThread) [custom_components.kidschores] Updated reward 'a new toy' with ID: e3f0fd94-1b42-4db7-b4c8-dd084565c5c2
2025-02-24 08:55:46.720 DEBUG (MainThread) [custom_components.kidschores] Updated reward '$5' with ID: fd6534b9-e3b3-4e45-9cd8-f7b98eff2ca2
2025-02-24 08:55:46.720 INFO (MainThread) [custom_components.kidschores] Starting global badge recalculation
2025-02-24 08:55:46.720 DEBUG (MainThread) [custom_components.kidschores] Manually updated kidschores_coordinator data
2025-02-24 08:55:46.720 INFO (MainThread) [custom_components.kidschores] Badge recalculation complete
2025-02-24 08:55:46.721 DEBUG (MainThread) [custom_components.kidschores] Finished fetching kidschores_coordinator data in 0.000 seconds (success: True)
2025-02-24 08:55:46.722 INFO (MainThread) [custom_components.kidschores] KidsChores services have been registered successfully
2025-02-24 08:55:46.768 INFO (MainThread) [custom_components.kidschores] Data saved successfully to storage
2025-02-24 08:55:46.778 INFO (MainThread) [custom_components.kidschores] Data saved successfully to storage
2025-02-24 08:55:53.984 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready() (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/selector_events.py", line 1241, in _read_ready
    self._protocol.datagram_received(data, addr)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/kasa/discover.py", line 377, in datagram_received
    device = device_func(info, config)
  File "/usr/local/lib/python3.13/site-packages/kasa/discover.py", line 742, in _get_device_instance_legacy
    device_class = cast(type[IotDevice], Discover._get_device_class(info))
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/kasa/discover.py", line 722, in _get_device_class
    return get_device_class_from_sys_info(info)
  File "/usr/local/lib/python3.13/site-packages/kasa/device_factory.py", line 145, in get_device_class_from_sys_info
    return TYPE_TO_CLASS[IotDevice._get_device_type_from_sys_info(sysinfo)]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: <DeviceType.Camera: 'camera'>
2025-02-24 08:55:54.118 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready() (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/selector_events.py", line 1241, in _read_ready
    self._protocol.datagram_received(data, addr)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/kasa/discover.py", line 377, in datagram_received
    device = device_func(info, config)
  File "/usr/local/lib/python3.13/site-packages/kasa/discover.py", line 742, in _get_device_instance_legacy
    device_class = cast(type[IotDevice], Discover._get_device_class(info))
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/kasa/discover.py", line 722, in _get_device_class
    return get_device_class_from_sys_info(info)
  File "/usr/local/lib/python3.13/site-packages/kasa/device_factory.py", line 145, in get_device_class_from_sys_info
    return TYPE_TO_CLASS[IotDevice._get_device_type_from_sys_info(sysinfo)]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: <DeviceType.Camera: 'camera'>
2025-02-24 08:55:54.349 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready() (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/selector_events.py", line 1241, in _read_ready
    self._protocol.datagram_received(data, addr)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/kasa/discover.py", line 377, in datagram_received
    device = device_func(info, config)
  File "/usr/local/lib/python3.13/site-packages/kasa/discover.py", line 742, in _get_device_instance_legacy
    device_class = cast(type[IotDevice], Discover._get_device_class(info))
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/kasa/discover.py", line 722, in _get_device_class
    return get_device_class_from_sys_info(info)
  File "/usr/local/lib/python3.13/site-packages/kasa/device_factory.py", line 145, in get_device_class_from_sys_info
    return TYPE_TO_CLASS[IotDevice._get_device_type_from_sys_info(sysinfo)]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: <DeviceType.Camera: 'camera'>
2025-02-24 08:55:54.361 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready() (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/selector_events.py", line 1241, in _read_ready
    self._protocol.datagram_received(data, addr)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/kasa/discover.py", line 377, in datagram_received
    device = device_func(info, config)
  File "/usr/local/lib/python3.13/site-packages/kasa/discover.py", line 742, in _get_device_instance_legacy
    device_class = cast(type[IotDevice], Discover._get_device_class(info))
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/kasa/discover.py", line 722, in _get_device_class
    return get_device_class_from_sys_info(info)
  File "/usr/local/lib/python3.13/site-packages/kasa/device_factory.py", line 145, in get_device_class_from_sys_info
    return TYPE_TO_CLASS[IotDevice._get_device_type_from_sys_info(sysinfo)]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: <DeviceType.Camera: 'camera'>
2025-02-24 08:55:54.368 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready() (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/selector_events.py", line 1241, in _read_ready
    self._protocol.datagram_received(data, addr)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/kasa/discover.py", line 377, in datagram_received
    device = device_func(info, config)
  File "/usr/local/lib/python3.13/site-packages/kasa/discover.py", line 742, in _get_device_instance_legacy
    device_class = cast(type[IotDevice], Discover._get_device_class(info))
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/kasa/discover.py", line 722, in _get_device_class
    return get_device_class_from_sys_info(info)
  File "/usr/local/lib/python3.13/site-packages/kasa/device_factory.py", line 145, in get_device_class_from_sys_info
    return TYPE_TO_CLASS[IotDevice._get_device_type_from_sys_info(sysinfo)]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: <DeviceType.Camera: 'camera'>
2025-02-24 08:55:57.171 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready() (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/selector_events.py", line 1241, in _read_ready
    self._protocol.datagram_received(data, addr)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/kasa/discover.py", line 377, in datagram_received
    device = device_func(info, config)
  File "/usr/local/lib/python3.13/site-packages/kasa/discover.py", line 742, in _get_device_instance_legacy
    device_class = cast(type[IotDevice], Discover._get_device_class(info))
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/kasa/discover.py", line 722, in _get_device_class
    return get_device_class_from_sys_info(info)
  File "/usr/local/lib/python3.13/site-packages/kasa/device_factory.py", line 145, in get_device_class_from_sys_info
    return TYPE_TO_CLASS[IotDevice._get_device_type_from_sys_info(sysinfo)]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: <DeviceType.Camera: 'camera'>
2025-02-24 08:56:01.357 INFO (MainThread) [custom_components.kidschores] KidsChores setup complete for entry: 01JMQ79VZR5GPFD7T5KDAN06RS
2025-02-24 08:56:08.778 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esphome-web-277288 @ 192.168.3.44: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.3.44', port=6053))]: [Errno 113] Connect call failed ('192.168.3.44', 6053) (SocketAPIError)
2025-02-24 08:56:08.795 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for moisture_leak_detector @ 192.168.3.30: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.3.30', port=6053))]: [Errno 113] Connect call failed ('192.168.3.30', 6053) (SocketAPIError)
2025-02-24 09:01:00.324 DEBUG (MainThread) [custom_components.kidschores] Finished fetching kidschores_coordinator data in 0.016 seconds (success: True)
2025-02-24 09:06:00.307 DEBUG (MainThread) [custom_components.kidschores] Finished fetching kidschores_coordinator data in 0.024 seconds (success: True)```

**Comment by ccpk1** [comment]
As I dig deeper, it looks like the new dashboard code is functioning correctly. However, I noticed that `"chore_name: Unknown Chore"` is appearing in your sensor data. This indicates that the dashboard isn't able to locate matching buttons for the `"Unknown Chore"` name as expected.  

The issue occurs when a **chore with an open claim is deleted**, leaving behind incomplete data. This is a **known issue** that has already been addressed in the latest **KidsChores integration update (0.2.2)** released this morning.  

🔗 **Reference Links:**  
- **Issue originally discussed yesterday with a manual fix:** [Dashboard Thread](https://community.home-assistant.io/t/introducing-the-kidschores-and-rewards-dashboard/849869/55?u=ccpk1)  
- **Fix listed in this morning’s release notes (7th bullet point):** [Integration Release Notes](https://community.home-assistant.io/t/kidschores-family-chore-management-integration/827719/54?u=ccpk1)  

I see that you're already updated to **0.2.2**, so let’s wait for @ad-ha to weigh in.

**Comment by ad-ha** [comment]
Hi,

I am on the phone and checking the whole log, not just related to the integration is quite hard.

Any pending chore approval not related to a chore should be automatically deleted, on the new 0.2.2 version.

I would consider, in you case, edit the pending_chore_approvals and pending_reward_approvals, from the `/config/.storage/kidschores_data ` and leave it `= [] ` and then reload the integration.

This should fix the problem. Wither that or fully start the integration from scratch.

**Comment by nickceward** [comment]
I just had the same thing happen after realising the ID was different to the chore name I wet through entities and corrected but the no name approval was still showing on dashboard.

I made reset all action and it went

**Comment by AustinSoundsOK** [comment]
> Hi,
> 
> I am on the phone and checking the whole log, not just related to the integration is quite hard.
> 
> Any pending chore approval not related to a chore should be automatically deleted, on the new 0.2.2 version.
> 
> I would consider, in you case, edit the pending_chore_approvals and pending_reward_approvals, from the `/config/.storage/kidschores_data ` and leave it `= [] ` and then reload the integration.
> 
> This should fix the problem. Wither that or fully start the integration from scratch.


This fixed the issue! Thanks!

**Comment by ad-ha** [comment]
Glad it worked out for all of you. Cheers
